[workspace]
members = ["bootloader", "kernel"]

[workspace.package]
version = "0.1.0"
edition = "2021"

[profile.dev]
panic = "abort"
opt-level = "z"
strip = true

[profile.release]
panic = "abort"
opt-level = "z"
strip = true
