[package]
name = "bootloader-uefi"
version.workspace = true
edition.workspace = true

[dependencies]
uefi = { version = "0.34", features = ["panic_handler", "qemu"] }
common = { path = "../common" }
x86_64 = "0.15"
